name: Python CI

on:
  push:
    branches: [main]
    paths:
      - 'python/**'
      - '.github/workflows/python-ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'python/**'
      - '.github/workflows/python-ci.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4

    - uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        enable-cache: true
        cache-dependency-glob: "python/uv.lock"

    - name: Install dependencies
      working-directory: ./python
      run: uv sync --dev

    - name: Format check
      working-directory: ./python
      run: uv run ruff format --check src/

    - name: Lint
      working-directory: ./python
      run: uv run ruff check src/

    - name: Type check
      working-directory: ./python
      run: uv run mypy src/

    - name: Test
      working-directory: ./python
      run: uv run pytest -v