name: Rust CI

on:
  push:
    branches: [main]
    paths:
      - 'rust/**'
      - '.github/workflows/rust-ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'rust/**'
      - '.github/workflows/rust-ci.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4

    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: rust

    - name: Format check
      working-directory: ./rust
      run: cargo fmt --check

    - name: Lint
      working-directory: ./rust
      run: cargo clippy -- -D warnings

    - name: Type check
      working-directory: ./rust
      run: cargo check

    - name: Test
      working-directory: ./rust
      run: cargo test --verbose