name: Rust CI

on:
  push:
    branches: [main]
    paths:
      - 'rust/**'
  pull_request:
    branches: [main]
    paths:
      - 'rust/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: rustup toolchain install stable --profile minimal --no-self-update
    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: rust
    - working-directory: ./rust
      run: |
        cargo fmt --check
        cargo check
        cargo clippy --all-targets --all-features -- -D warnings
        cargo test --verbose