name: TypeScript CI

on:
  push:
    branches: [main]
    paths:
      - "typescript/**"
  pull_request:
    branches: [main]
    paths:
      - "typescript/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - working-directory: ./typescript
        run: |
          deno install
          deno fmt --check
          deno lint
          deno test
