name: TypeScript CI

on:
  push:
    branches: [main]
    paths:
      - 'typescript/**'
  pull_request:
    branches: [main]
    paths:
      - 'typescript/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typescript:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - working-directory: ./typescript
      run: |
        bun install
        bunx biome check
        bunx tsc --noEmit
        bun test