name: TypeScript CI

on:
  push:
    branches: [main]
    paths:
      - 'typescript/**'
  pull_request:
    branches: [main]
    paths:
      - 'typescript/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typescript:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: bun install
      working-directory: ./typescript
      run: bun install

    - name: biome check
      working-directory: ./typescript
      run: bunx biome check

    - name: tsc --noEmit
      working-directory: ./typescript
      run: bunx tsc --noEmit

    - name: bun test
      working-directory: ./typescript
      run: bun test