name: TypeScript CI

on:
  push:
    branches: [main]
    paths:
      - 'typescript/**'
      - '.github/workflows/typescript-ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'typescript/**'
      - '.github/workflows/typescript-ci.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  typescript:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4

    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Cache bun dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.bun/install/cache
          typescript/node_modules
        key: ${{ runner.os }}-bun-${{ hashFiles('typescript/bun.lock') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Install dependencies
      working-directory: ./typescript
      run: bun install

    - name: Format check
      working-directory: ./typescript
      run: bunx prettier --check .

    - name: Lint
      working-directory: ./typescript
      run: bunx eslint

    - name: Type check
      working-directory: ./typescript
      run: bunx tsc --noEmit

    - name: Test
      working-directory: ./typescript
      run: bunx vitest run --reporter=verbose